name: Release

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  release:
    name: Build and Release
    runs-on: macos-latest
    permissions: write-all
    steps:
      - name: Initialize custom bot
        id: bot
        uses: starburst997/custom-bot-init@v1
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.bot.outputs.token }}

      - name: Tag Version
        id: version
        uses: starburst997/auto-version@v1
        with:
          git-push: false

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: false

      - name: Setup Fastlane Match SSH Key
        if: ${{ secrets.MATCH_GIT_URL != '' }}
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}

      - name: Install Bundler Dependencies
        run: |
          cd sample
          bundle install

      - name: Install npm Dependencies
        run: |
          cd sample
          npm install

      - name: Build Sample App (Signed with Fastlane Match)
        if: ${{ secrets.MATCH_GIT_URL != '' }}
        env:
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
        run: |
          cd sample
          bundle exec fastlane mac release

      - name: Build Sample App (Unsigned)
        if: ${{ secrets.MATCH_GIT_URL == '' }}
        run: |
          cd sample
          bundle exec fastlane mac test_build

      - name: Manage Deployment
        uses: starburst997/deployment-actions@v1
        with:
          environment: npm
          environment-url: https://www.npmjs.com/package/@jdboivin/react-native-video-desktop

      - name: Publish NPM
        uses: starburst997/npm-publish@v1
        with:
          version: ${{ steps.version.outputs.version }}

      - name: Generate changelog and create release
        uses: starburst997/commits-logs@v1
        with:
          token: ${{ steps.bot.outputs.token }}
          git-push: true
          artifacts: |
            sample/dist/*.zip
