name: Release

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Initialize custom bot
        id: bot
        uses: starburst997/custom-bot-init@v1
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.bot.outputs.token }}

      - name: Tag Version
        id: version
        uses: starburst997/auto-version@v1

      - name: Manage Deployment
        uses: starburst997/deployment-actions@v1
        with:
          environment: npm
          environment-url: https://www.npmjs.com/package/@jdboivin/react-native-video-desktop

      - name: Publish NPM
        uses: starburst997/npm-publish@v1
        with:
          version: ${{ steps.version.outputs.version }}

      - name: Generate changelog and create release
        uses: starburst997/commits-logs@v1
        with:
          token: ${{ steps.bot.outputs.token }}
